server:
 port: 8888
 
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
   
spring:
 application:
  name: config-server

 cloud:
  config:
   server:
    git:
     #配置git仓库地址
     uri: https://github.com/youziliang/springcloud-config.git
     #配置仓库路径（應該是指搜索倉庫下的哪個目錄）
     searchPaths: {application}
     #访问git仓库的用户名
     username: 
     #访问git仓库的用户密码（如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写）
     password: 
   #配置仓库的分支
   label: master