server:
 port: 8769
 
spring:
 application:
  name: zuul-server
  
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

zuul:
 prefix: /api
 strip-prefix: false
 routes:
  test:
   path: /test
   serviceId: eurka-producer
  test-1:
   path: /test-1
   serviceId: eurka-producer